apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: application-task-1
spec:
  containers:
    - name: application-task-1
      image: registry.skbkontur.ru/mc-k8s/task-1:application
      env:
        - name: USER_NAME
          value: "Введите тут свое имя"
      resources:
        limits:
          memory: "200Mi"
          cpu: "300m" 
        requests:
          memory: "100Mi"
          cpu: "200m"
