apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application-back
spec:
  replicas: 1 # Укажите кол-во реплик от 1 до 5
  template:
    metadata:
      labels:
        app: application-back
    spec:
      containers:
      - name: application-backend
        image: registry.skbkontur.ru/mc-k8s/task-2:backend
        ports:
        - containerPort: 5001
        env:
          - name: USER_NAME
            value: "Введите тут свое имя"
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m" 
          requests:
            memory: "100Mi"
            cpu: "200m"
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application-front
spec:
  replicas: 1 # Укажите кол-во реплик от 1 до 5
  template:
    metadata:
      labels:
        app: application-front
    spec:
      containers:
      - name: application-front
        image: registry.skbkontur.ru/mc-k8s/task-2:front
        ports:
          - containerPort: 5000
        env:
          - name: BACKEND_URL
            value: http://application-back:80
          - name: USER_NAME
            value: "Введите тут свое имя"
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m" 
          requests:
            memory: "100Mi"
            cpu: "200m"
